const express=require("express"),multer=require("multer"),fs=require("fs/promises"),path=require("path"),crypto=require("crypto");
const app=express(),PORT=+process.env.PORT||3000,BASE=(process.env.PUBLIC_BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,""),USER=process.env.ADMIN_USER||"admin",PASS=process.env.ADMIN_PASSWORD||"change-me-now";
const DATA=path.join(__dirname,"data"),PUB=path.join(__dirname,"public"),QF=path.join(DATA,"qsos.json"),SF=path.join(DATA,"settings.json"),WF=path.join(DATA,"wavelog.json");
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024}});
const defaults={stationName:"My Station",homeGrid:"KP20",bands:[],modes:[],autoRotate:true,showStats:true,showCallsigns:false,maxPaths:2500};
const wdefaults={baseUrl:"",token:"",stationIds:"",autoSyncMinutes:0,lastSyncId:0,lastSyncAt:null,lastSyncError:null};
let syncing=false;
async function read(f,d){try{return JSON.parse(await fs.readFile(f,"utf8"))}catch{return structuredClone(d)}}
async function write(f,v){await fs.mkdir(DATA,{recursive:true});let t=f+"."+crypto.randomUUID();await fs.writeFile(t,JSON.stringify(v,null,2),{mode:0o600});await fs.rename(t,f)}
function eq(a,b){a=Buffer.from(String(a));b=Buffer.from(String(b));return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function auth(req,res,next){let h=req.headers.authorization||"";if(!h.startsWith("Basic "))return res.set("WWW-Authenticate",'Basic realm="QSO Trails Admin"').status(401).end();let [u,p=""]=Buffer.from(h.slice(6),"base64").toString().split(":");if(!eq(u,USER)||!eq(p,PASS))return res.set("WWW-Authenticate",'Basic realm="QSO Trails Admin"').status(401).end();next()}
function grid(g){g=String(g||"").trim().toUpperCase();if(!/^[A-R]{2}\d{2}([A-X]{2})?(\d{2})?$/.test(g))return null;let lon=(g.charCodeAt(0)-65)*20-180+ +g[2]*2,lat=(g.charCodeAt(1)-65)*10-90+ +g[3],xs=2,ys=1;if(g.length>=6){xs=2/24;ys=1/24;lon+=(g.charCodeAt(4)-65)*xs;lat+=(g.charCodeAt(5)-65)*ys}if(g.length>=8){xs/=10;ys/=10;lon+=+g[6]*xs;lat+=+g[7]*ys}return{lat:lat+ys/2,lon:lon+xs/2}}
function coord(v,lat){if(v==null||v==="")return null;let n=+v;if(Number.isFinite(n)&&Math.abs(n)<=(lat?90:180))return n;let m=String(v).trim().toUpperCase().match(/^([NSEW])?\s*(\d{1,3})[:\s](\d{1,2}(?:\.\d+)?)\s*([NSEW])?$/);if(!m)return null;n=+m[2]+ +m[3]/60;if((m[1]||m[4])==="S"||(m[1]||m[4])==="W")n=-n;return Math.abs(n)<=(lat?90:180)?n:null}
function pos(r){let lat=coord(r.LAT??r.lat,true),lon=coord(r.LON??r.lon,false);return lat!=null&&lon!=null?{lat,lon}:grid(r.GRIDSQUARE??r.gridsquare)}
function adif(t){let out=[],tag=/<([A-Z0-9_]+):(\d+)(?::[^>]*)?>([^<]*)/ig;for(let c of String(t).split(/<EOR>/i)){let r={},m;tag.lastIndex=0;while(m=tag.exec(c))r[m[1].toUpperCase()]=m[3].slice(0,+m[2]).trim();if(Object.keys(r).length)out.push(r)}return out}
function norm(r,src="wavelog"){let p=pos(r);if(!p)return null;let d=String(r.qso_date||r.QSO_DATE||""),[date,time=""]=d.split(/\s+/,2);return{source:src,sourceId:+r.id||0,call:r.call||r.CALL||"?",band:String(r.band||r.BAND||"").toUpperCase(),mode:String(r.submode||r.SUBMODE||r.mode||r.MODE||"").toUpperCase(),date,time:time.replace(/:/g,"")||r.TIME_ON||"",grid:r.gridsquare||r.GRIDSQUARE||"",lat:p.lat,lon:p.lon}}
const uniq=a=>[...new Set(a.filter(Boolean))].sort((x,y)=>x.localeCompare(y,undefined,{numeric:true}));
async function state(){let qsos=await read(QF,[]),settings={...defaults,...await read(SF,defaults)};return{qsos,settings,meta:{total:qsos.length,bands:uniq(qsos.map(q=>q.band)),modes:uniq(qsos.map(q=>q.mode))}}}
function cleanSettings(x,m){let home=String(x.homeGrid||"").toUpperCase();if(!grid(home))throw Error("Invalid Maidenhead locator");let bs=new Set(m.bands),ms=new Set(m.modes);return{stationName:String(x.stationName||"My Station").slice(0,80),homeGrid:home,bands:(x.bands||[]).map(String).map(v=>v.toUpperCase()).filter(v=>bs.has(v)),modes:(x.modes||[]).map(String).map(v=>v.toUpperCase()).filter(v=>ms.has(v)),autoRotate:!!x.autoRotate,showStats:!!x.showStats,showCallsigns:!!x.showCallsigns,maxPaths:Math.max(100,Math.min(10000,+x.maxPaths||2500))}}
function pub(q,s){let allow=new Set(s.bands),modes=new Set(s.modes);return q.filter(x=>allow.has(x.band)&&modes.has(x.mode)).map(x=>{let o={band:x.band,mode:x.mode,date:x.date,time:x.time,grid:x.grid,lat:x.lat,lon:x.lon};if(s.showCallsigns)o.call=x.call;return o})}
function wlurl(base){base=String(base||"").trim().replace(/\/+$/,"");if(!/^https?:\/\//.test(base))throw Error("Wavelog URL must be http(s)");return /\/index\.php$/i.test(base)?base+"/api/v2/qso":base+"/index.php/api/v2/qso"}
async function wcfg(){return{...wdefaults,...await read(WF,wdefaults)}}
async function reqjson(u,c){let ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),30000);try{let r=await fetch(u,{headers:{Authorization:`Bearer ${c.token}`,Accept:"application/json"},signal:ctl.signal}),t=await r.text(),j=t?JSON.parse(t):{};if(!r.ok)throw Error(j?.error?.message||j?.message||r.statusText);return j}finally{clearTimeout(tm)}}
async function sync(full=false){if(syncing)throw Error("Sync already running");syncing=true;try{let c=await wcfg();if(!c.baseUrl||!c.token)throw Error("Configure Wavelog URL and token");let since=full?0:+c.lastSyncId||0,page=1,rows=[],max=since;for(;;page++){let u=new URL(wlurl(c.baseUrl));u.searchParams.set("page",page);u.searchParams.set("per_page","5000");if(since)u.searchParams.set("since_id",since);if(c.stationIds)u.searchParams.set("station_id",c.stationIds);let j=await reqjson(u,c),d=Array.isArray(j.data)?j.data:[];rows.push(...d);for(let r of d)max=Math.max(max,+r.id||0);if(!j.meta?.has_more)break}let n=rows.map(r=>norm(r)).filter(Boolean),old=full?[]:await read(QF,[]),map=new Map(old.map(q=>[(q.sourceId?`w:${q.sourceId}`:crypto.createHash("sha1").update(JSON.stringify(q)).digest("hex")),q]));for(let q of n)map.set(`w:${q.sourceId}`,q);let all=[...map.values()];await write(QF,all);c={...c,lastSyncId:max,lastSyncAt:new Date().toISOString(),lastSyncError:null};await write(WF,c);return{fetched:rows.length,usable:n.length,stored:all.length,lastSyncId:max}}catch(e){let c=await wcfg();await write(WF,{...c,lastSyncError:String(e.message||e)});throw e}finally{syncing=false}}
async function autosync(){let c=await wcfg(),min=+c.autoSyncMinutes||0;if(!min||!c.baseUrl||!c.token||syncing)return;let last=c.lastSyncAt?Date.parse(c.lastSyncAt):0;if(Date.now()-last<min*60000)return;try{await sync(false)}catch(e){console.error(e.message)}}
app.disable("x-powered-by");app.use(express.json({limit:"1mb"}));app.use("/assets",express.static(PUB,{index:false}));
app.get("/",(_,r)=>r.redirect("/embed"));app.get("/embed",(_,r)=>r.sendFile(path.join(PUB,"embed.html")));app.get("/admin",auth,(_,r)=>r.sendFile(path.join(PUB,"admin.html")));
app.get("/api/public",async(_,r)=>{let{qsos,settings}=await state(),p=pub(qsos,settings);r.json({settings:{stationName:settings.stationName,homeGrid:settings.homeGrid,autoRotate:settings.autoRotate,showStats:settings.showStats,maxPaths:settings.maxPaths},qsoCount:p.length,qsos:p})});
app.get("/api/admin/state",auth,async(_,r)=>{let s=await state(),w=await wcfg();r.json({meta:s.meta,settings:s.settings,wavelog:{...w,token:undefined,tokenConfigured:!!w.token,syncing},iframeHtml:`<iframe src="${BASE}/embed" width="100%" height="620" style="border:0" loading="lazy"></iframe>`})});
app.post("/api/admin/settings",auth,async(q,r)=>{try{let s=await state(),v=cleanSettings(q.body,s.meta);await write(SF,v);r.json({ok:true,visibleQsos:pub(s.qsos,v).length})}catch(e){r.status(400).json({error:e.message})}});
app.post("/api/admin/upload",auth,upload.single("adif"),async(q,r)=>{if(!q.file)return r.status(400).json({error:"Choose ADIF"});let rows=adif(q.file.buffer.toString()).map(x=>norm(x,"adif")).filter(Boolean);await write(QF,rows);r.json({usableQsos:rows.length})});
app.post("/api/admin/wavelog/config",auth,async(q,r)=>{try{let c=await wcfg(),b=String(q.body.baseUrl||"").replace(/\/+$/,"");let token=String(q.body.token||"").trim()||c.token,stationIds=String(q.body.stationIds||"").trim(),autoSyncMinutes=Math.max(0,+q.body.autoSyncMinutes||0);if(b)wlurl(b);await write(WF,{...c,baseUrl:b,token,stationIds,autoSyncMinutes});r.json({ok:true})}catch(e){r.status(400).json({error:e.message})}});
app.post("/api/admin/wavelog/test",auth,async(_,r)=>{try{let c=await wcfg(),u=new URL(wlurl(c.baseUrl));u.searchParams.set("per_page","1");await reqjson(u,c);r.json({ok:true})}catch(e){r.status(400).json({error:e.message})}});
app.post("/api/admin/wavelog/sync",auth,async(q,r)=>{try{r.json({ok:true,...await sync(!!q.body?.full)})}catch(e){r.status(400).json({error:e.message})}});
fs.mkdir(DATA,{recursive:true}).then(()=>app.listen(PORT,"0.0.0.0",()=>console.log(`QSO Trails ${BASE}`)));setInterval(autosync,60000).unref();
